# Generated by Django 3.1.2 on 2020-10-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('image', models.ImageField(upload_to='authors/', verbose_name='Изображение')),
                ('position', models.CharField(max_length=256, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата написания')),
                ('url', models.SlugField(blank=True, max_length=160, unique=True)),
                ('journal', models.CharField(max_length=512, verbose_name='Жкрнал')),
                ('authors', models.ManyToManyField(related_name='article_authors', to='posts.Author', verbose_name='Авторы')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['date'],
            },
        ),
    ]
