# Generated by Django 3.1.2 on 2020-10-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=512)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.CharField(max_length=512, verbose_name='Журнал'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=160, unique=True),
        ),
    ]
