# Generated by Django 3.1.2 on 2020-10-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_article_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='abbr',
            field=models.SlugField(blank=True, max_length=20, verbose_name='Аббривеатура'),
        ),
    ]
