# Generated by Django 3.1.2 on 2020-10-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201022_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='abbr',
            field=models.SlugField(max_length=20, unique=True, verbose_name='Аббривеатура'),
        ),
    ]
