# Generated by Django 3.1.2 on 2020-10-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201022_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='abbr',
            new_name='slug',
        ),
    ]
