# Generated by Django 3.1.2 on 2020-11-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20201116_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='istina_author_id',
        ),
        migrations.AddField(
            model_name='author',
            name='istina_author_ref',
            field=models.CharField(blank=True, max_length=160, unique=True, verbose_name='Ссылка на сотрудника'),
        ),
    ]
