# Generated by Django 3.1.2 on 2020-11-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20201121_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='istina_article_id',
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='istina_author_ref',
            field=models.CharField(max_length=160, unique=True, verbose_name='Ссылка на сотрудника'),
        ),
    ]
