# Generated by Django 3.1.2 on 2021-02-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20201121_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='article_authors', to='posts.Author', verbose_name='Авторы'),
        ),
    ]
