# Generated by Django 3.1.2 on 2021-03-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210225_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='firstname',
            field=models.CharField(default='name', max_length=25, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='lastname',
            field=models.CharField(default='lastname', max_length=40, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='thirdname',
            field=models.CharField(default='thirdname', max_length=40, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
