# Generated by Django 3.1.2 on 2021-03-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210322_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='firstname',
            field=models.CharField(max_length=25, verbose_name='Имя на английском с заглавной буквы'),
        ),
        migrations.AlterField(
            model_name='author',
            name='lastname',
            field=models.CharField(max_length=40, verbose_name='Фамилия на английском с заглавной буквы'),
        ),
        migrations.AlterField(
            model_name='author',
            name='thirdname',
            field=models.CharField(max_length=40, verbose_name='Отчество на английском с заглавной буквы'),
        ),
    ]
