# Generated by Django 3.2.6 on 2021-10-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20210326_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='google_sholar_reference',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True, verbose_name='Ссылка на сотрудника в системе Google Sholar'),
        ),
        migrations.AlterField(
            model_name='author',
            name='istina_author_ref',
            field=models.CharField(max_length=160, unique=True, verbose_name='Ссылка на сотрудника в системе истина'),
        ),
    ]
