# Generated by Django 3.2.9 on 2022-01-09 13:50

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20211018_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date', django.db.models.functions.text.Length('authors')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='google_sholar_reference',
        ),
        migrations.AddField(
            model_name='author',
            name='wos_researcher_id',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True, verbose_name='Ссылка на сотрудника в системе WOS'),
        ),
    ]
