# Generated by Django 3.2.9 on 2024-02-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='sequence_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Порядковый номер представления автора в списке команды'),
        ),
    ]
