version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    env_file: 
      ./proj/.env
    volumes:
      - ./pgdata:/var/lib/posgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    links:
      - db:db
    env_file: 
      ./proj/.env
    depends_on: 
      - db
    command: python manage.py runserver 0.0.0.0:8000
volumes: 
  pgdata: