version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    env_file: 
      ./proj/.env
    ports: 
      - "5432"
    volumes:
      - ./pgdata:/var/lib/posgresql/data
  web:
    build: /app
    ports: 
      - "8000:8000"
    env_file: 
      ./proj/.env
    depends_on: 
      - db
    command: python manage.py runserver
volumes: 
  pgdata: