version: '3.7'

services:
  web:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./proj/.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=belozersky
volumes:
  postgres_data: